import type { ComponentType, SVGProps } from "react";
import ClaudeSource from "~icons/logos/claude-icon";
import OpenAISource from "~icons/logos/openai-icon";
import ArrowLeftSource from "~icons/lucide/arrow-left";
import BanSource from "~icons/lucide/ban";
import BookOpenSource from "~icons/lucide/book-open";
import BotSource from "~icons/lucide/bot";
import BrainSource from "~icons/lucide/brain";
import BrushCleaningSource from "~icons/lucide/brush-cleaning";
import CheckSource from "~icons/lucide/check";
import ChevronDownSource from "~icons/lucide/chevron-down";
import ChevronRightSource from "~icons/lucide/chevron-right";
import ChevronUpSource from "~icons/lucide/chevron-up";
import CircleSource from "~icons/lucide/circle";
import CheckCircle2Source from "~icons/lucide/circle-check";
import XCircleSource from "~icons/lucide/circle-x";
import Clock3Source from "~icons/lucide/clock-3";
import CloudSource from "~icons/lucide/cloud";
import CopySource from "~icons/lucide/copy";
import CpuSource from "~icons/lucide/cpu";
import DownloadSource from "~icons/lucide/download";
import Globe2Source from "~icons/lucide/earth";
import MoreHorizontalSource from "~icons/lucide/ellipsis";
import ExternalLinkSource from "~icons/lucide/external-link";
import EyeSource from "~icons/lucide/eye";
import EyeOffSource from "~icons/lucide/eye-off";
import FileSource from "~icons/lucide/file";
import fileIconSvgSource from "~icons/lucide/file?raw";
import FilePenLineSource from "~icons/lucide/file-pen-line";
import FileTextSource from "~icons/lucide/file-text";
import FolderSource from "~icons/lucide/folder";
import folderIconSvgSource from "~icons/lucide/folder?raw";
import FolderOpenSource from "~icons/lucide/folder-open";
import FolderTreeSource from "~icons/lucide/folder-tree";
import GlobeSource from "~icons/lucide/globe";
import HistorySource from "~icons/lucide/history";
import ImageIconSource from "~icons/lucide/image";
import ImageOffSource from "~icons/lucide/image-off";
import InfoSource from "~icons/lucide/info";
import KeySource from "~icons/lucide/key";
import LightbulbSource from "~icons/lucide/lightbulb";
import Link2Source from "~icons/lucide/link-2";
import Loader2Source from "~icons/lucide/loader-circle";
import LoaderCircleSource from "~icons/lucide/loader-circle";
import LockSource from "~icons/lucide/lock";
import Maximize2Source from "~icons/lucide/maximize-2";
import MessageSquareSource from "~icons/lucide/message-square";
import MessageSquareTextSource from "~icons/lucide/message-square-text";
import Minimize2Source from "~icons/lucide/minimize-2";
import MinusSource from "~icons/lucide/minus";
import MonitorSmartphoneSource from "~icons/lucide/monitor-smartphone";
import MoonSource from "~icons/lucide/moon";
import PanelLeftSource from "~icons/lucide/panel-left";
import PanelLeftCloseSource from "~icons/lucide/panel-left-close";
import PaperclipSource from "~icons/lucide/paperclip";
import Edit3Source from "~icons/lucide/pen-line";
import PencilSource from "~icons/lucide/pencil";
import PinSource from "~icons/lucide/pin";
import PinOffSource from "~icons/lucide/pin-off";
import PlaySource from "~icons/lucide/play";
import PlugSource from "~icons/lucide/plug";
import PlusSource from "~icons/lucide/plus";
import RadioSource from "~icons/lucide/radio";
import RefreshCwSource from "~icons/lucide/refresh-cw";
import ScrollTextSource from "~icons/lucide/scroll-text";
import SearchSource from "~icons/lucide/search";
import SendSource from "~icons/lucide/send";
import ServerSource from "~icons/lucide/server";
import SettingsSource from "~icons/lucide/settings";
import Settings2Source from "~icons/lucide/settings-2";
import Share2Source from "~icons/lucide/share-2";
import ShieldSource from "~icons/lucide/shield";
import SparklesSource from "~icons/lucide/sparkles";
import SquareSource from "~icons/lucide/square";
import SquarePenSource from "~icons/lucide/square-pen";
import SunSource from "~icons/lucide/sun";
import TerminalSource from "~icons/lucide/terminal";
import Trash2Source from "~icons/lucide/trash-2";
import AlertTriangleSource from "~icons/lucide/triangle-alert";
import UploadSource from "~icons/lucide/upload";
import WifiSource from "~icons/lucide/wifi";
import WifiOffSource from "~icons/lucide/wifi-off";
import WrenchSource from "~icons/lucide/wrench";
import XSource from "~icons/lucide/x";
import ZapSource from "~icons/lucide/zap";
import FileTypeGeminiSource from "~icons/vscode-icons/file-type-gemini";

type IconSource = ComponentType<SVGProps<SVGSVGElement> & { title?: string }>;

type IconProps = SVGProps<SVGSVGElement> & {
  absoluteStrokeWidth?: boolean;
  size?: number | string;
  title?: string;
};

export type IconComponent = ComponentType<IconProps>;

function createIcon(Source: IconSource): IconComponent {
  return function Icon({
    absoluteStrokeWidth: _absoluteStrokeWidth,
    height,
    size,
    width,
    ...props
  }) {
    const nextProps: IconProps = { ...props };
    if (size !== undefined) {
      nextProps.width = width ?? size;
      nextProps.height = height ?? size;
    } else {
      if (width !== undefined) nextProps.width = width;
      if (height !== undefined) nextProps.height = height;
    }
    return <Source {...nextProps} />;
  };
}

export const AlertTriangle = createIcon(AlertTriangleSource);
export const ClaudeIcon = createIcon(ClaudeSource);
export const FileTypeGeminiIcon = createIcon(FileTypeGeminiSource);
export const ArrowLeft = createIcon(ArrowLeftSource);
export const Ban = createIcon(BanSource);
export const BookOpen = createIcon(BookOpenSource);
export const Bot = createIcon(BotSource);
export const Brain = createIcon(BrainSource);
export const BrushCleaning = createIcon(BrushCleaningSource);
export const Check = createIcon(CheckSource);
export const CheckCircle2 = createIcon(CheckCircle2Source);
export const ChevronDown = createIcon(ChevronDownSource);
export const ChevronRight = createIcon(ChevronRightSource);
export const ChevronUp = createIcon(ChevronUpSource);
export const Circle = createIcon(CircleSource);
export const Clock3 = createIcon(Clock3Source);
export const Cloud = createIcon(CloudSource);
export const Copy = createIcon(CopySource);
export const Cpu = createIcon(CpuSource);
export const Download = createIcon(DownloadSource);
export const Edit3 = createIcon(Edit3Source);
export const ExternalLink = createIcon(ExternalLinkSource);
export const Eye = createIcon(EyeSource);
export const EyeOff = createIcon(EyeOffSource);
export const File = createIcon(FileSource);
export const FilePenLine = createIcon(FilePenLineSource);
export const FileText = createIcon(FileTextSource);
export const Folder = createIcon(FolderSource);
export const FolderOpen = createIcon(FolderOpenSource);
export const FolderTree = createIcon(FolderTreeSource);
export const Globe = createIcon(GlobeSource);
export const Globe2 = createIcon(Globe2Source);
export const History = createIcon(HistorySource);
export const ImageIcon = createIcon(ImageIconSource);
export const ImageOff = createIcon(ImageOffSource);
export const Info = createIcon(InfoSource);
export const Key = createIcon(KeySource);
export const Link2 = createIcon(Link2Source);
export const Lightbulb = createIcon(LightbulbSource);
export const Loader2 = createIcon(Loader2Source);
export const LoaderCircle = createIcon(LoaderCircleSource);
export const Lock = createIcon(LockSource);
export const Maximize2 = createIcon(Maximize2Source);
export const MessageSquare = createIcon(MessageSquareSource);
export const MessageSquareText = createIcon(MessageSquareTextSource);
export const Minimize2 = createIcon(Minimize2Source);
export const Minus = createIcon(MinusSource);
export const MonitorSmartphone = createIcon(MonitorSmartphoneSource);
export const Moon = createIcon(MoonSource);
export const MoreHorizontal = createIcon(MoreHorizontalSource);
export const OpenaiChatgptIcon = createIcon(OpenAISource);
export const PanelLeft = createIcon(PanelLeftSource);
export const PanelLeftClose = createIcon(PanelLeftCloseSource);
export const Paperclip = createIcon(PaperclipSource);
export const Pencil = createIcon(PencilSource);
export const Pin = createIcon(PinSource);
export const PinOff = createIcon(PinOffSource);
export const Play = createIcon(PlaySource);
export const Plug = createIcon(PlugSource);
export const Plus = createIcon(PlusSource);
export const Radio = createIcon(RadioSource);
export const RefreshCw = createIcon(RefreshCwSource);
export const ScrollText = createIcon(ScrollTextSource);
export const Search = createIcon(SearchSource);
export const Send = createIcon(SendSource);
export const Server = createIcon(ServerSource);
export const Settings = createIcon(SettingsSource);
export const Settings2 = createIcon(Settings2Source);
export const Share2 = createIcon(Share2Source);
export const Shield = createIcon(ShieldSource);
export const Sparkles = createIcon(SparklesSource);
export const Square = createIcon(SquareSource);
export const SquarePen = createIcon(SquarePenSource);
export const Sun = createIcon(SunSource);
export const Terminal = createIcon(TerminalSource);
export const Trash2 = createIcon(Trash2Source);
export const Upload = createIcon(UploadSource);
export const Wifi = createIcon(WifiSource);
export const WifiOff = createIcon(WifiOffSource);
export const Wrench = createIcon(WrenchSource);
export const X = createIcon(XSource);
export const XCircle = createIcon(XCircleSource);
export const Zap = createIcon(ZapSource);
const fileIconSvg = fileIconSvgSource as unknown as string;
const folderIconSvg = folderIconSvgSource as unknown as string;

export { fileIconSvg, folderIconSvg };
