package server

type websocketRequestHandler func(*websocketConnection, websocketRequest)

var websocketRequestHandlers = map[string]websocketRequestHandler{
	"status.get": func(c *websocketConnection, req websocketRequest) {
		_ = c.writeResponse(req.ID, c.sm.Status())
	},
	"fs.roots":                       (*websocketConnection).handleFsRoots,
	"fs.list_dirs":                   (*websocketConnection).handleFsListDirs,
	"fs.create_project_folder":       (*websocketConnection).handleFsCreateProjectFolder,
	"fs.list":                        (*websocketConnection).handleFsList,
	"fs.read_editable_text":          (*websocketConnection).handleFsReadEditableText,
	"fs.write_text":                  (*websocketConnection).handleFsWriteText,
	"fs.create_dir":                  (*websocketConnection).handleFsCreateDir,
	"fs.rename":                      (*websocketConnection).handleFsRename,
	"fs.delete":                      (*websocketConnection).handleFsDelete,
	"history.list":                   (*websocketConnection).handleHistoryList,
	"history.workdirs":               (*websocketConnection).handleHistoryWorkdirs,
	"history.shared_list":            (*websocketConnection).handleHistorySharedList,
	"history.get":                    (*websocketConnection).handleHistoryGet,
	"history.rename":                 (*websocketConnection).handleHistoryRename,
	"history.pin":                    (*websocketConnection).handleHistoryPin,
	"history.share.get":              (*websocketConnection).handleHistoryShareGet,
	"history.share.set":              (*websocketConnection).handleHistoryShareSet,
	"history.delete":                 (*websocketConnection).handleHistoryDelete,
	"history.truncate":               (*websocketConnection).handleHistoryTruncate,
	"providers.list":                 (*websocketConnection).handleProviderList,
	"settings.get":                   (*websocketConnection).handleSettingsGet,
	"settings.update":                (*websocketConnection).handleSettingsUpdate,
	"skills.list":                    (*websocketConnection).handleSkillFilesList,
	"mentions.list":                  (*websocketConnection).handleFileMentionList,
	"skills.read-metadata":           (*websocketConnection).handleSkillMetadataRead,
	"skills.read-text":               (*websocketConnection).handleSkillTextRead,
	"skills.manage":                  (*websocketConnection).handleSkillManage,
	"chat.start":                     (*websocketConnection).handleChatStart,
	"chat.resume":                    (*websocketConnection).handleChatResume,
	"chat.attach":                    (*websocketConnection).handleChatAttach,
	"chat.detach":                    (*websocketConnection).handleChatDetach,
	"chat.cancel":                    (*websocketConnection).handleChatCancel,
	"files.preview":                  (*websocketConnection).handleUploadedImagePreview,
	"memory.manage":                  (*websocketConnection).handleMemoryManage,
	"terminal.shell_options":         (*websocketConnection).handleTerminalRequest,
	"terminal.list":                  (*websocketConnection).handleTerminalRequest,
	"terminal.create":                (*websocketConnection).handleTerminalRequest,
	"terminal.attach":                (*websocketConnection).handleTerminalRequest,
	"terminal.input":                 (*websocketConnection).handleTerminalRequest,
	"terminal.resize":                (*websocketConnection).handleTerminalRequest,
	"terminal.rename":                (*websocketConnection).handleTerminalRequest,
	"terminal.close":                 (*websocketConnection).handleTerminalRequest,
	"terminal.close_project":         (*websocketConnection).handleTerminalRequest,
	"terminal.detach":                (*websocketConnection).handleTerminalDetach,
	"git.status":                     (*websocketConnection).handleGitRequest,
	"git.branches":                   (*websocketConnection).handleGitRequest,
	"git.init":                       (*websocketConnection).handleGitRequest,
	"git.switch_branch":              (*websocketConnection).handleGitRequest,
	"git.create_branch":              (*websocketConnection).handleGitRequest,
	"git.diff":                       (*websocketConnection).handleGitRequest,
	"git.log":                        (*websocketConnection).handleGitRequest,
	"git.commit_details":             (*websocketConnection).handleGitRequest,
	"git.compare_commit_with_remote": (*websocketConnection).handleGitRequest,
	"git.commit_diff":                (*websocketConnection).handleGitRequest,
	"git.stage":                      (*websocketConnection).handleGitRequest,
	"git.stage_all":                  (*websocketConnection).handleGitRequest,
	"git.unstage":                    (*websocketConnection).handleGitRequest,
	"git.unstage_all":                (*websocketConnection).handleGitRequest,
	"git.discard":                    (*websocketConnection).handleGitRequest,
	"git.discard_all":                (*websocketConnection).handleGitRequest,
	"git.add_to_gitignore":           (*websocketConnection).handleGitRequest,
	"git.commit":                     (*websocketConnection).handleGitRequest,
	"git.fetch":                      (*websocketConnection).handleGitRequest,
	"git.pull":                       (*websocketConnection).handleGitRequest,
	"git.set_remote":                 (*websocketConnection).handleGitRequest,
	"git.push":                       (*websocketConnection).handleGitRequest,
	"cron.manage":                    (*websocketConnection).handleCronManage,
	"provider.models":                (*websocketConnection).handleProviderModels,
}
